name: Deploy to TestFlight (iOS Only)

on:
  push:
    branches: [TestFlight] 

jobs:
  build:
    name: Install and Build iOS
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: mobile  

    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo + EAS CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Inject environment variables from secrets
        run: |
          echo "EXPO_PUBLIC_DEV_FLAG=${{ secrets.EXPO_PUBLIC_DEV_FLAG }}" >> $GITHUB_ENV
          echo "EXPO_PUBLIC_BACKEND_URL=${{ secrets.EXPO_PUBLIC_BACKEND_URL }}" >> $GITHUB_ENV
          echo "EXPO_PUBLIC_SENSOR_DATA_URL=${{ secrets.EXPO_PUBLIC_SENSOR_DATA_URL }}" >> $GITHUB_ENV
          echo "EXPO_PUBLIC_GOOGLE_API_KEY=${{ secrets.EXPO_PUBLIC_GOOGLE_API_KEY }}" >> $GITHUB_ENV
          echo "EXPO_APPLE_ID=${{ secrets.EXPO_APPLE_ID }}" >> $GITHUB_ENV

      - name: Build iOS App (for TestFlight)
        run: eas build --platform ios --profile production --non-interactive

      - name: Submit to TestFlight
        run: eas submit --platform ios --profile production --non-interactive --latest






