name: Run Tests

on:
  workflow_dispatch: {}
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  frontend-tests:
    name: Expo / Jest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/sep2025_project_team_004
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432; do echo "⏳ waiting for postgres…"; sleep 1; done
      - name: Check for missing migrations
        run: python manage.py makemigrations --check --dry-run
      - name: Apply migrations
        run: python manage.py migrate --noinput
      - name: Run pytest with coverage
        run: pytest --ds=config.settings.test --nomigrations --cov=. --cov-report=xml --cov-report=term-missing
      - name: Upload back-end coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage.xml
